plone/plonetheme.barceloneta

- plonetheme/barceloneta/theme/less/portlets.plone.less
This pull request provides styles to keep the display of broken products in the Plone add-ons control panel in accordance with existing categories of products on that page.
This PR should only be merged if https://github.com/plone/Products.CMFPlone/pull/420 is merged as it is only required if HTML elements added in that PR are present.
This addresses plone/Products.CMFPlone#419
> Add styles for new "broken products" section in add-ons control panel

- plonetheme/barceloneta/theme/rules.xml
When extending the barceloneta-theme in my own theme with a xi-include like this:
<?xml version="1.0" encoding="utf-8"?>
<rules xmlns="http://namespaces.plone.org/diazo"
xmlns:css="http://namespaces.plone.org/diazo/css"
xmlns:xhtml="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:xi="http://www.w3.org/2001/XInclude">
<xi:include href="/++theme++barceloneta/rules.xml" />
</rules>
Diazo throws the following error on rendering (the error is shown in the diazo-debug iframe without a traceback)
runtime error, element 'div' [96:0]
Variable 'central' has not been declared. [0:0]
runtime error, element 'div' [96:0]
Internal error: Failed to evaluate the AVT of attribute 'class'. [0:0]
When moving the rule-element <xsl:variable name="central">...</xsl:variable> …
> fix extending barceloneta with xi:include

- plonetheme/barceloneta/profiles/default/registry.xml
This can be used in custom themes like this:
@import "@{barcelonetaLessPath}/search.plone.less";
Do we need something in plone.app.upgrade to load this profile?
> add barcelonetaLessPath less variable to registry

- plonetheme/barceloneta/configure.zcml
- plonetheme/barceloneta/profiles/registerless/metadata.xml
- plonetheme/barceloneta/profiles/registerless/registry.xml
- plonetheme/barceloneta/theme/less/barceloneta.plone.export.less
Add profile for register all the Barceloneta LESS resources for later use in Diazo themes as variables. This allow to being able to compile them with the plone-compile-resources as well.
> Allow including barceloneta resources in a custom themes as variables

- CHANGES.rst
- plonetheme/barceloneta/theme/backend.xml
In the scenario where somebody has a diazo bundle for their front-end theme but uses the backend theme for control panel/editing etc, we don't want to include the diazo bundles as it may clash with the barceloneta theme.
> Don't include diazo bundle in backend theme

- CHANGES.rst
- plonetheme/barceloneta/theme/less/barceloneta-compiled.css
- plonetheme/barceloneta/theme/less/header.plone.less
The search button in Plone 5.0.3 is styled in order to aptly incorporate 'Search' keyword in different translations. Referring to issue: https://github.com/plone/Products.CMFPlone/issues/1154
For instance:
is converted into-
> Fix for Search button problem in Plone 5.0.x

- plonetheme/barceloneta/theme/less/header.plone.less
this was probably a leftover from a previous incarnation, removing the css makes it revert to correct (top) alignment.
> aligment tickbox for 'this section only' is off

- CHANGES.rst
- plonetheme/barceloneta/theme/rules.xml
Refs:
- https://github.com/plone/Products.CMFPlone/pull/2324
- https://github.com/plone/Products.CMFPlone/pull/2398
- https://github.com/plone/Products.CMFPlone/pull/2399
Fixes:
- https://github.com/plone/Products.CMFPlone/issues/2322
- https://github.com/plone/Products.CMFPlone/issues/2395
- https://github.com/plone/Products.CMFPlone/issues/2531
Merge together:
https://github.com/plone/Products.CMFPlone/pull/2563
https://github.com/plone/plonetheme.barceloneta/pull/165
https://github.com/plone/plone.app.upgrade/pull/180
> Do not strip the #edit-bar section from the toolbar.

- CHANGES.rst
- plonetheme/barceloneta/theme/rules.xml
- setup.py
remove colophon and copyright too, when not present in  content.
bump version to 1.10.0 because of breaking changes.
> Update footer rules

- news/2952.bugfix
- plonetheme/barceloneta/configure.zcml
This is for our use of the `plone:static` directive.
See https://github.com/plone/Products.CMFPlone/issues/2952
> Load zcml of plone.resource.

- CHANGES.rst
- plonetheme/barceloneta/theme/less/behaviors.plone.less
- plonetheme/barceloneta/theme/less/modal.plone.less
Reverts plone/plonetheme.barceloneta#184 because it removes `CHANGES.rst`.
> Revert "Modal and News Image Container Improvements and Fixes"

- news/212.feature
- plonetheme/barceloneta/theme/rules.xml
We import the rules.xml form our custom theme product, unfortunaly this does not work with the existing include:
```2020-08-11 11:55:37,447 ERROR   [plone.subrequest:38][waitress-0] Error handling subrequest to /grid-col-marker.xml
Traceback (most recent call last):
File "/home/gomez/.cache/buildout/eggs/Zope-4.5-py3.8.egg/ZPublisher/BaseRequest.py", line 518, in traverse
subobject = self.traverseName(object, entry_name)
File "/home/gomez/.cache/buildout/eggs/Zope-4.5-py3.8.egg/ZPublisher/BaseRequest.py", line 349, in traverseName
ob2 = adapter.publishTraverse(self, name)
File "/home/gomez/.cache/buildout/eggs/Zope-4.5-py3.8.egg/ZPublisher/BaseRequest.py", line 136, in publishTraverse
subobject = object[name]
File "/home/gomez/.cache/buildout/eggs/Zope-4.5-py3.8.egg/OFS/ObjectManager.py", …
```
> Change to relative xml include path to make external includes possible

- plonetheme/barceloneta/overrides/plone.app.content.browser.templates.select_default_page.pt
- plonetheme/barceloneta/overrides/plone.app.content.browser.templates.select_default_view.pt
Following the guidelines in https://github.com/plone/Products.CMFPlone/issues/2967 and https://github.com/plone/plone.app.content/issues/196 I've updated the following templates from plone.app.content:
- plone.app.content.browser.templates.select_default_view.pt
- plone.app.content.browser.templates.select_default_page.pt
Decisions:
- Use buttons instead of inputs for the form submissions; 
- Use 'btn-primary' for "form.buttons.Save" actions
- Use 'btn-secondary' for "form.buttons.Cancel" actions
> Update plone.app.content templates to Bootstrap 4 

- news/3191.bugfix
- plonetheme/barceloneta/theme/backend.xml
when copying the toolbar html into the theme using backend.xml, as was fixed two years to in the normal rules.xml
> Also leave #edit-bar intact 

- news/3191.bugfix
- plonetheme/barceloneta/theme/backend.xml
as was fixed two years to in the normal rules.xml
> Also leave #edit-bar intact when copying the toolbar html into the theme using backend.xml

- news/241.feature
- scss/header.scss
This just uses the mixin to make portal-header a bootstrap row. The code does it already but not set the flex-wrap: wrap by default, while the row does it. The change is enabled only when viewport is over than $nav-main-breakpoint.
Note: bootstrap mixin row add some margin to the row, so using 0rem as parameter for make-row permit the logo to be aligned with the main navigation as before.
> Use make-row mixin for portal-header thus it has the flex-wrap: wrap

- news/281.bugfix
- plonetheme/barceloneta/theme/rules.xml
This branch fixes https://github.com/plone/plonetheme.barceloneta/issues/281
In addition, I went ahead and included an extra fix. When you create a static text portlet, you can specify a "Details link" that will be used to wrap the header and footer of the portlet itself with an `<a>` tag. This works fine with portlets in the left and the right, but the footer portlets loose the link for the header. 
Since it was a small fix, I decided to include here. Let me know if I should revert that change, and create a separate issue and PR for that.
> Footer portlet fixes

- news/303.bugfix
- plonetheme/barceloneta/theme/rules.xml
The reason for this is, that this view often misses some viewlets or viewlet managers and is very confusing.
It is helping people more when it stays unstyled.
> disable diazo for manage-viewlets view

- plonetheme/barceloneta/theme/rules.xml
Solution for the problem describe here : https://community.plone.org/t/error-theme-inherited-from-barceloneta-footer-portlets-count/8455
> Move 'footer_portlets' and 'footer_portlets_count' variables

- news/359.bugfix
- plonetheme/barceloneta/theme/backend.xml
pat-plone-modal works fine now and also this would remove "nav-link dropdown-item" classes, unstyling the menu entries
[yurj]
> don't drop class attribute in edit bar for backend.xml - Plone 6.0

- news/358.bugfix
- plonetheme/barceloneta/theme/backend.xml
pat-plone-modal works fine now and also this would remove "nav-link dropdown-item" classes, unstyling the menu entries.
> don't drop class attribute in edit bar for backend.xml

- news/376.feature
- plonetheme/barceloneta/theme/backend.xml
- plonetheme/barceloneta/theme/manifest.cfg
Looking at this rule, for example:
```xml
<after css:theme-children="head">
<link href="++theme++barceloneta/css/barceloneta.css"
rel="stylesheet"
/>
</after>
```
the css will be loaded relative to the content. This is problematic:
- different url for the same css file, cache problems
- traversing private content can lead to "Insufficient privileges" while the resource itself is public
This PR add the portal_url variable in the theme parameters (manifest.cfg) and apply it in backend.xml
> Add the portal_url parameter to be used with Diazo rules
