CHANGES.rst, index.html
Please see https://github.com/plone/mockup/pull/485 and https://github.com/plone/mockup/issues/483
=> The pat-modal pattern has been renamed to pat-plone-modal

plonetheme/barceloneta/theme/rules.xml
Prevent quoting of inline JavaScript code
=> fixed rules for copying content

CHANGES.rst, plonetheme/barceloneta/theme/less/print.plone.less
Hides it in print. Good to go?
=> Hide search / ptools / breadcrumbs

plonetheme/barceloneta/theme/backend.xml, plonetheme/barceloneta/theme/index.html
For https://github.com/plone/Products.CMFPlone/issues/465
Needs to reviewed by @bloodbare or @vangheem or someone who knows resource bundles and bareceonleta more than me.
=> A cutdown version of barceloneta to include in your theme to save you making a custom backend theme

plonetheme/barceloneta/profiles/default/registry.xml
Reverts plone/plonetheme.barceloneta#37
=> Revert "add barcelonetaLessPath less variable to registry"

CHANGES.rst, plonetheme/barceloneta/theme/backend.xml, plonetheme/barceloneta/theme/index.html, plonetheme/barceloneta/theme/rules.xml
=> In rules prefer css selectors

plonetheme/barceloneta/theme/index.html, plonetheme/barceloneta/theme/rules.xml
Fixes https://github.com/plone/Products.CMFPlone/issues/974
Only together with https://github.com/plone/Products.CMFPlone/pull/992
=> include hero-element from a view @@hero

CHANGES.rst, plonetheme/barceloneta/theme/backend.xml, plonetheme/barceloneta/theme/rules.xml
Closes plone/Products.CMFPlone#1105
=> Discard duplicated ids for columns 

CHANGES.rst, plonetheme/barceloneta/theme/manifest.cfg
References https://github.com/plone/Products.CMFPlone/issues/1220#issuecomment-155383088
=> Add comment to alert on duplicate resource registering

CHANGES.rst, README.rst
=> Follow Plone best practice on readme

CHANGES.rst, plonetheme/barceloneta/theme/rules.xml
Although not a good approach for front-end, is possible that templates provides inline style (nowadays this is a convenient way to not enter in the new resource registry world).
=> inline style tags are now included

CHANGES.rst, plonetheme/barceloneta/profiles/registerless/registry.xml
I missed that while developing [plonetheme.persona](https://github.com/collective/plonetheme.persona).
=> Add barceloneta-mixin-font to the registerless profile.

plonetheme/barceloneta/theme/less/barceloneta.plone.export.less
Its required by barceloneta-fonts.
=> Add barceloneta-mixin-font to plone.export.less.

CHANGES.rst, plonetheme/barceloneta/theme/index.html, plonetheme/barceloneta/theme/rules.xml
Part of https://github.com/plone/Products.CMFPlone/issues/1430
=> Fix html validation

CHANGES.rst, plonetheme/barceloneta/theme/backend.xml, plonetheme/barceloneta/theme/rules.xml
Refs b80f5973d27e3227c3cadee8be090be4539163f7. Thanks for the report, @vikas-parashar.
I think that's ok, right, @sneridagh ?
I don't think we need Jenkins in this case before merge. No tests would catch this change.
=> Remove 'fridged' offcanvas feature

CHANGES.rst, plonetheme/barceloneta/theme/rules.xml
=> Fix for icons in tool bar when no link is there #110

plonetheme/barceloneta/theme/less/header.plone.less
corrected the alignment of search box in mobile view.
someone please review it.
https://github.com/plone/Products.CMFPlone/issues/2332
=> updated header.plone.less

CHANGES.rst, plonetheme/barceloneta/theme/index.html, plonetheme/barceloneta/theme/rules.xml
Have content container before column1 before column2 and adjust bootstrap grid classes to visually pull/push columns into the known 3 column layout.
=> Adjust content columns

CHANGES.rst, plonetheme/barceloneta/theme/less/barceloneta-compiled.css, plonetheme/barceloneta/theme/less/sitenav.plone.less
https://github.com/plone/Products.CMFPlone/issues/2516
=> Plip 2516 navigation

plonetheme/barceloneta/overrides/plone.app.event.portlets.portlet_events.pt, plonetheme/barceloneta/overrides/plone.app.portlets.browser.templates.edit-manager-contextual.pt, plonetheme/barceloneta/overrides/plone.app.portlets.browser.templates.edit-manager-macros.pt, plonetheme/barceloneta/overrides/plone.app.portlets.portlets.login.pt, plonetheme/barceloneta/overrides/plone.app.portlets.portlets.news.pt, plonetheme/barceloneta/overrides/plone.app.portlets.portlets.rss.pt, plonetheme/barceloneta/overrides/plone.portlet.collection.collection.pt, plonetheme/barceloneta/overrides/plone.portlet.static.static.pt, plonetheme/barceloneta/theme/scss/bootstrap.scss, plonetheme/barceloneta/theme/scss/portlets.plone.scss, plonetheme/barceloneta/theme/scss/variables.bootstrap.scss
refactoring:
News-Portlet
Event-Portlet
Static-Portlet
=> Portlet - Switch to Bootstrap Card Element

news/264.bugfix, plonetheme/barceloneta/theme/backend.xml, plonetheme/barceloneta/theme/rules.xml
=> Be more specific where replacing the head title element

news/304.bugfix, plonetheme/barceloneta/theme/index.html
=> prefix icon patch in index.html with ++theme++barceloneta to prevent broken icon in other themes

news/307.bugfix, package-lock.json, package.json, plonetheme/barceloneta/configure.zcml, plonetheme/barceloneta/profiles/default/metadata.xml, plonetheme/barceloneta/profiles/default/registry/tinymce.xml, plonetheme/barceloneta/theme/tinymce/tinymce-ui-content.css
fixes #307 
does this need an upgrade step?
/cc @thet @MrTango
=> Add TinyMCE UI css

README.md, news/338.documentation
Fixes https://github.com/plone/plonetheme.barceloneta/issues/338
=> Fix broken links in the readme.

news/379.bugfix, package-lock.json, package.json
- upgrade development resources
- no public CSS changed
=> upgrade development dependencies. No CSS resources changed.
